##########################################################################
# @brief FRDM_MCXW71 additional .conf settings
# @author Jan-Willem Smaal <usenet@gispen.org
##########################################################################

##########################################################################
# Tune these settings to reduce the RAM footprint
##########################################################################
#CONFIG_IDLE_STACK_SIZE=512
# Heap: enough for CFB + SH1122 conversion buffer
CONFIG_HEAP_MEM_POOL_SIZE=16448
# Stacks: enough to avoid corruption during SH1122 writes
#CONFIG_MAIN_STACK_SIZE=4096
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
#CONFIG_ISR_STACK_SIZE=4096


##########################################################################
# Configure I2C displays 
##########################################################################
CONFIG_SH1122=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=n
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=y

# EOF
